//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotterWinds.Modules.Products {
    
    
    public partial class ProductContent {
        
        /// <summary>
        /// ImagesDisplay1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HotterWinds.Modules.Products.ProductImagesDisplay ImagesDisplay1;
        
        /// <summary>
        /// ProductTopDisplay1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HotterWinds.Modules.Products.ProductTopDisplay ProductTopDisplay1;
        
        /// <summary>
        /// SimilarLinks1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HotterWinds.Modules.Products.HWRelatedProducts SimilarLinks1;
        
        /// <summary>
        /// ProductDescription1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HotterWinds.Modules.Products.ProductDescription ProductDescription1;
    }
}
