//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotterWinds {
    
    
    public partial class NewCatalog {
        
        /// <summary>
        /// CatalogSiteMap1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HotterWinds.Modules.Catalog.CatalogSiteMapNew CatalogSiteMap1;
        
        /// <summary>
        /// CatalogSiteMapDetail1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HotterWinds.Modules.Catalog.CatalogSiteMapDetailNew CatalogSiteMapDetail1;
        
        /// <summary>
        /// Breadcrumbs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HotterWinds.Modules.Breadcrumbs Breadcrumbs;
        
        /// <summary>
        /// NewCatalogProducts1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HotterWinds.Modules.Catalog.NewCatalogProducts NewCatalogProducts1;
        
        /// <summary>
        /// PrettyPager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HotterWinds.Modules.PrettyPager PrettyPager1;
        
        /// <summary>
        /// NewFilters1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HotterWinds.Modules.Catalog.NewFilters NewFilters1;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new HotterWinds.Main Master {
            get {
                return ((HotterWinds.Main)(base.Master));
            }
        }
    }
}
