//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotterWinds {
    
    
    public partial class Product {
        
        /// <summary>
        /// Breadcrumbs1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HotterWinds.Modules.Breadcrumbs Breadcrumbs1;
        
        /// <summary>
        /// ProductContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HotterWinds.Modules.Products.ProductContent ProductContent;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new HotterWinds.Main Master {
            get {
                return ((HotterWinds.Main)(base.Master));
            }
        }
    }
}
