<?xml version="1.0" encoding="utf-8"?><Database Name="PriceMe" Class="AttributeCategoryComparisonDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.0.0.26;Initial Catalog=PriceMe;User ID=sa" SettingsObjectName="PriceMe.RichAttributeDisplayTool.Properties.Settings" SettingsPropertyName="PriceMeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AttributeCategoryComparison" Member="AttributeCategoryComparisons">
    <Type Name="AttributeCategoryComparison">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Always" IsVersion="true" />
      <Column Name="Aid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsCompareAttribute" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsHigherBetter" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Top10" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Top20" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Top30" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Average" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Bottom30" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Bottom20" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Bottom10" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Createdon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modifiedon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>